version: '2.1'
services:
    redis:
        image: 'redis:4.0.11'
        command: ["redis-server", "--appendonly", "yes"]
    mysql:
        image: mysql:5.7
        command: --explicit_defaults_for_timestamp=1
        environment:
            - MYSQL_ROOT_PASSWORD=#AirFlow1
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
    webserver:
        image: turnerlabs/docker-airflow:latest
        restart: "no"
        links:
            - mysql
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
        volumes:
            - ./airflow:/usr/local/airflow
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
            interval: 30s
            timeout: 30s
            retries: 3
        entrypoint: /entrypoint.sh
    scheduler:
        image: turnerlabs/docker-airflow:latest
        restart: "no"
        links:
            - mysql            
            - redis
        volumes:
            - ./airflow:/usr/local/airflow
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
        command: scheduler
        entrypoint: /entrypoint.sh
    worker:
        image: turnerlabs/docker-airflow:latest
        restart: "no"
        links:
            - redis
        volumes:
            - ./airflow:/usr/local/airflow
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: worker
        entrypoint: /entrypoint.sh