version: '2.1'
services:
    redis:
        image: 'redis:4.0.11'
    mysql:
        image: mysql:5.7
        command: --explicit_defaults_for_timestamp=1
        environment:
            - MYSQL_ROOT_PASSWORD=#AirFlow1
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
    webserver:
        image: turnerlabs/docker-airflow:latest
        restart: always
        links:
            - mysql
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
        volumes:
            - ./airflow:/usr/local/airflow/airflow
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    flower:
        image: turnerlabs/docker-airflow:latest
        restart: always
        links:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower
    scheduler:
        image: turnerlabs/docker-airflow:latest
        restart: always
        links:
            - mysql            
            - redis
        volumes:
            - ./airflow:/usr/local/airflow/airflow
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
        command: scheduler
    worker:
        image: turnerlabs/docker-airflow:latest
        restart: always
        links:
            - redis
        volumes:
            - ./airflow:/usr/local/airflow/airflow
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: worker
