version: '2.1'
services:
    redis:
        image: 'redis:4.0.11'
        environment:
            - REDIS_DEFAULT_USER=airflow
            - REDIS_DEFAULT_PASS=airflow
            - REDIS_DEFAULT_VHOST=airflowhost
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=#AirFlow1
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
    webserver:
        image: turnerlabs/docker-airflow:latest
        restart: always
        depends_on:
            - mysql
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
            - REDIS_DEFAULT_USER=airflow
            - REDIS_DEFAULT_PASS=airflow
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: turnerlabs/docker-airflow:latest
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_DEFAULT_USER=airflow
            - REDIS_DEFAULT_PASS=airflow
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: turnerlabs/docker-airflow:latest
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DB=airflow
            - REDIS_DEFAULT_USER=airflow
            - REDIS_DEFAULT_PASS=airflow
        command: scheduler

    worker:
        image: turnerlabs/docker-airflow:latest
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DB=airflow
            - REDIS_DEFAULT_USER=airflow
            - REDIS_DEFAULT_PASS=airflow
        command: worker
